### ISSUE TITLE
ogmp.net is down 

### ISSUE THREAD

**Issue by MatteCrystal** [ogmp/ogmp_server#7]
ogmp.net is down, I cant connect to any servers and I don't run Linux so I cant host my own. would love to play this game with my friends especially since its coming out of beta soon.

**Comment by citadelservers** [comment]
@OGMP-Surak @Gyrth 

Is the project still alive? We'd like to provide rentable hosting for this project. If you need hosting for master server or web hosting we can provide this for free to support your project.

**Comment by EmpSurak** [comment]
Hey @citadelservers, thanks for the offer! But it isn't ;)
